openapi: 3.0.0
paths:
  /api/analytics/visa:
    get:
      summary: Get visa analytics overview
      description: Retrieve comprehensive visa analytics and statistics
      tags:
        - Analytics
      security:
        - bearerAuth: []
      parameters:
        - name: timeframe
          in: query
          schema:
            type: string
            enum: [week, month, quarter, year]
            default: month
          description: Time frame for analytics
        - name: visaType
          in: query
          schema:
            type: string
            enum: [F1, J1, H1B, OPT, CPT, Other]
          description: Filter by visa type
        - name: status
          in: query
          schema:
            type: string
            enum: [submitted, in_review, approved, rejected, pending]
          description: Filter by status
      responses:
        '200':
          description: Analytics data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      overview:
                        type: object
                        properties:
                          totalCases:
                            type: integer
                            example: 1250
                          approvedCases:
                            type: integer
                            example: 980
                          pendingCases:
                            type: integer
                            example: 200
                          rejectedCases:
                            type: integer
                            example: 70
                          approvalRate:
                            type: number
                            format: float
                            example: 78.4
                      byType:
                        type: array
                        items:
                          type: object
                          properties:
                            visaType:
                              type: string
                              example: F1
                            count:
                              type: integer
                              example: 450
                            approvalRate:
                              type: number
                              format: float
                              example: 85.2
                      timeline:
                        type: array
                        items:
                          type: object
                          properties:
                            date:
                              type: string
                              format: date
                            submissions:
                              type: integer
                            approvals:
                              type: integer
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/analytics/visa/cases:
    get:
      summary: Get visa cases with filtering
      description: Retrieve visa cases with advanced filtering and pagination
      tags:
        - Analytics
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Number of cases per page
        - name: visaType
          in: query
          schema:
            type: string
            enum: [F1, J1, H1B, OPT, CPT, Other]
          description: Filter by visa type
        - name: status
          in: query
          schema:
            type: string
            enum: [submitted, in_review, approved, rejected, pending]
          description: Filter by status
        - name: processingCenter
          in: query
          schema:
            type: string
          description: Filter by processing center
      responses:
        '200':
          description: Visa cases retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      cases:
                        type: array
                        items:
                          $ref: '#/components/schemas/VisaCase'
                      pagination:
                        $ref: '#/components/schemas/Pagination'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    
    post:
      summary: Create a new visa case
      description: Add a new visa case for tracking
      tags:
        - Analytics
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - visaType
                - status
                - applicationDate
              properties:
                visaType:
                  type: string
                  enum: [F1, J1, H1B, OPT, CPT, Other]
                  example: F1
                status:
                  type: string
                  enum: [submitted, in_review, approved, rejected, pending]
                  example: submitted
                applicationDate:
                  type: string
                  format: date
                  example: "2024-01-15"
                processingCenter:
                  type: string
                  example: "National Benefits Center"
                caseNumber:
                  type: string
                  example: "MSC2190000001"
                priority:
                  type: string
                  enum: [normal, premium]
                  default: normal
                description:
                  type: string
                  example: "F1 visa application for Master's program"
      responses:
        '201':
          description: Visa case created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Visa case created successfully
                  data:
                    type: object
                    properties:
                      case:
                        $ref: '#/components/schemas/VisaCase'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/analytics/visa/cases/{id}:
    get:
      summary: Get visa case details
      description: Retrieve detailed information about a specific visa case
      tags:
        - Analytics
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Visa case ID
      responses:
        '200':
          description: Visa case details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      case:
                        $ref: '#/components/schemas/VisaCase'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    
    put:
      summary: Update visa case
      description: Update an existing visa case
      tags:
        - Analytics
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Visa case ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [submitted, in_review, approved, rejected, pending]
                approvalDate:
                  type: string
                  format: date
                processingCenter:
                  type: string
                caseNumber:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Visa case updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Visa case updated successfully
                  data:
                    type: object
                    properties:
                      case:
                        $ref: '#/components/schemas/VisaCase'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    
    delete:
      summary: Delete visa case
      description: Delete a visa case (soft delete)
      tags:
        - Analytics
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Visa case ID
      responses:
        '200':
          description: Visa case deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Visa case deleted successfully
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/analytics/visa/timeline/{id}:
    get:
      summary: Get visa case timeline
      description: Retrieve timeline and history for a specific visa case
      tags:
        - Analytics
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Visa case ID
      responses:
        '200':
          description: Visa case timeline retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      timeline:
                        type: array
                        items:
                          type: object
                          properties:
                            date:
                              type: string
                              format: date-time
                            event:
                              type: string
                              example: "Status changed to In Review"
                            previousStatus:
                              type: string
                              example: "submitted"
                            newStatus:
                              type: string
                              example: "in_review"
                            notes:
                              type: string
                              example: "Case transferred to National Benefits Center"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
